# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# If not configured otherwise, only run on commits
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(manifests/charts/.*/README*)|\.*svg$|\.*dot$
      - id: end-of-file-fixer
        exclude: ^(docs/|manifests/charts/.*/README*)|\.*svg$|\.*dot$
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: check-added-large-files
        exclude: ^(operator/config/crd/.*|docs/content/assets/.*)
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
        exclude: ^gradlew$
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        exclude: ^(README*|.github/.*)
        types_or:
          [
            sh,
            shell,
            bash,
            dockerfile,
            makefile,
            java,
            markdown,
          ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude: ^src/main/java/com/fluxninja/aperture/flowcontrol/
