version: 2.1

# this allows to use CircleCI's dynamic configuration feature
setup: true

executors:
  base-cimg-executor:
    docker:
      - image: cimg/base:2021.07

orbs:
  path-filtering: circleci/path-filtering@0.1.3
  continuation: circleci/continuation@0.3.1

workflows:
  version: 2
  filter-paths-main:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - not:
            matches:
              &is_not_empty_tag {
                value: << pipeline.git.tag >>,
                pattern: "^.+$",
              }
        - not: &scheduled
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
    jobs:
      - path-filtering/filter: &path_filtering_job
          base-revision: << pipeline.git.base_revision >>
          config-path: .circleci/continue-workflows.yml
          mapping: |
            src/main/java/com/fluxninja/aperture/sdk/.* updated-sdk true

  filter-paths-pr:
    when:
      and:
        - not:
            equal: [main, << pipeline.git.branch >>]
        - not:
            matches: *is_not_empty_tag
        - not: *scheduled
    jobs:
      - path-filtering/filter:
          <<: *path_filtering_job
          base-revision: main
